import type { TableProps } from "antd";

export const dataSource = [
  {
    country: "China",
    name: "SHANGHAI",
    portCode: "CNSHG",
    vesselsInPort: 2420,
    departures: 1376,
    arrivals: 1626,
    type: "Port",
    areaLocal: "East China Sea",
    areaGlobal: "Central China",
    otherPortNames: "SHANG HAI,YANGSHAN,CNSHA,CNSGH",
    id: "35af0c57-2941-4036-bf98-62a4c67a74e7",
    isActive: true,
    delflg: false,
    createDateTime: "2024-01-29T05:46:30.103Z",
    createdBy: "SYSTEM",
    lastChangedDateTime: "2024-01-29T05:46:30.103Z",
    lastChangedBy: "SYSTEM",
  },
  {
    country: "China",
    name: "NANTONG",
    portCode: "CNNTG",
    vesselsInPort: 1572,
    departures: 1173,
    arrivals: 1287,
    type: "Port",
    areaLocal: "East China Sea",
    areaGlobal: "Central China",
    otherPortNames: "NAN TONG",
    id: "f6305975-8730-4345-bb8b-2b2679b2ff27",
    isActive: true,
    delflg: false,
    createDateTime: "2024-01-29T05:46:30.139Z",
    createdBy: "SYSTEM",
    lastChangedDateTime: "2024-01-29T05:46:30.139Z",
    lastChangedBy: "SYSTEM",
  },
  {
    country: "China",
    name: "CJK",
    portCode: "CNCJK",
    vesselsInPort: 1529,
    departures: 343,
    arrivals: 370,
    type: "Anchorage",
    areaLocal: "East China Sea",
    areaGlobal: "Central China",
    otherPortNames: "CHANGJIANGKOU,CHANGJIANG KOU,CJK CN",
    id: "25bb73b6-1fd9-44c3-8ea2-bd8b7d81484a",
    isActive: true,
    delflg: false,
    createDateTime: "2024-01-29T05:46:30.139Z",
    createdBy: "SYSTEM",
    lastChangedDateTime: "2024-01-29T05:46:30.139Z",
    lastChangedBy: "SYSTEM",
  },
];

export const columns: TableProps<any>["columns"] = [
  {
    title: "Cuntry",
    dataIndex: "country",
    key: "country",
  },
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Port Code",
    dataIndex: "portCode",
    key: "portCode",
  },
  {
    title: "Vessels In Port",
    dataIndex: "vesselsInPort",
    key: "vesselsInPort",
  },
  {
    title: "Departures",
    dataIndex: "departures",
    key: "departures",
  },
  {
    title: "Arrivals",
    dataIndex: "arrivals",
    key: "arrivals",
  },
  {
    title: "Type",
    dataIndex: "type",
    key: "type",
  },
  {
    title: "Area Local",
    dataIndex: "areaLocal",
    key: "areaLocal",
  },
  {
    title: "Area Global",
    dataIndex: "areaGlobal",
    key: "areaGlobal",
  },
  {
    title: "Other Port Names",
    dataIndex: "otherPortNames",
    key: "otherPortNames",
  },
];
